function calcPlayer(){
	loader(['points'],n(10))
	
	loader(['room'],n(0))
	loader(['room_sub'],n(0))
	loader(['room_storage'],n(0))
	loader(['room_storage_dim1'],n(0))
	loader(['room_storage_dim1_progress'],n(0))
	loader(['room_distorted'],n(0))
	
	loader(['dim_1'],n(0))
	loader(['dim_1_additiona'],n(0))
	loader(['dim_2'],n(0))
	
	NotOmegaLoader(['hasRoomUpg1'],"false")
	loader(['roomUpgEff1'],n(0))
	NotOmegaLoader(['hasRoomUpg2'],"false")
	loader(['roomUpgEff2'],n(0))
	NotOmegaLoader(['hasRoomUpg3'],"false")
	NotOmegaLoader(['hasRoomUpg4'],"false")
	NotOmegaLoader(['hasRoomUpg5'],"false")
	NotOmegaLoader(['hasRoomUpg6'],"false")
	loader(['roomUpgEff6'],n(0))
	NotOmegaLoader(['hasRoomUpg7'],"false")
	loader(['roomUpgEff7'],n(0))
	NotOmegaLoader(['hasRoomUpg8'],"false")
	loader(['roomUpgEff8'],n(0))
	NotOmegaLoader(['hasRoomUpg9'],"false")
	NotOmegaLoader(['hasRoomUpg10'],"false")
	NotOmegaLoader(['hasRoomUpg11'],"false")
	NotOmegaLoader(['hasRoomUpg12'],"false")
	
	loader(['quark'],n(0))
	NotOmegaLoader(['showQuark'],"false")
	
	loader(['quark_red'],n(0))
	loader(['quark_green'],n(0))
	loader(['quark_blue'],n(0))
	
	loader(['red'],n(0))
	loader(['green'],n(0))
	loader(['blue'],n(0))
	loader(['yellow'],n(0))
	loader(['cyan'],n(0))
	loader(['magenta'],n(0))
	loader(['white'],n(0))
}
